pages:
  - name: ホーム - 未来
    path: /2024-03-01
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2024-02-01
  - name: 出走表
    path: /races/a370ba71-faa6-4896-8c58-563875481173/race-card
  - name: オッズ - 締め切り前
    path: /races/aff9bc7d-c240-4651-9a4c-d8c6f2823ffa/odds
  - name: オッズ - 締め切り後
    path: /races/bc4b5785-5004-486f-8dac-2f1ba3c4e70c/odds
  - name: 結果
    path: /races/bd52f3c9-5494-4153-87c3-d7d14787377c/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
