pages:
  - name: ホーム - 未来
    path: /2024-02-19
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2024-01-21
  - name: 出走表
    path: /races/6d1f3067-5cb5-4f53-8aaa-4a3531c48d21/race-card
  - name: オッズ - 締め切り前
    path: /races/b670f853-35c8-40c8-8522-acff7d246dc1/odds
  - name: オッズ - 締め切り後
    path: /races/17623704-a3ef-470b-ae8b-7481c5685ac2/odds
  - name: 結果
    path: /races/5d780db5-e3e8-44fa-8fe1-f4a3fddf18df/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
