pages:
  - name: ホーム - 未来
    path: /2024-03-01
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2024-02-01
  - name: 出走表
    path: /races/216a5486-be78-4e03-8214-e704d367af9f/race-card
  - name: オッズ - 締め切り前
    path: /races/7c57c699-55d8-46a3-a4c3-24e486b7070b/odds
  - name: オッズ - 締め切り後
    path: /races/776ae213-a0c7-4108-bf4c-d2dfa3aa5413/odds
  - name: 結果
    path: /races/c2405873-09e6-4433-a6bd-74b3dadafa4d/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
